version: '3'
services:
  app:
    container_name: voip
    build:
      context: .
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - BASE_URL=http://localhost:3000/
      - DB=mongodb://root:YouDareBreakMe@voip_db/
      - COOKIE_KEY=putsupersecretphrasehere
      - HTTPS=false
      - SIGNUPS=on
    ports:
      - 127.0.0.1:3000:3000

  db:
    container_name: voip_db
    image: mongo:6.0.13
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=YouDareBreakMe
    volumes:
      - ./db_data:/data/db
